print("Hello, I'm a student developer 👨‍💻")
print("Name: Rajesh V")
print("College: Ramaiah Institute Of Technology Bangaluru")
print("Interest: Programming, AI, Web Development")
print("Goal: To become a skilled software engineer 🚀")
